In [1]:
from Part_1_functions import *

## Функция нескольких переменных

$$
a = \alpha(x, y) = x + y
$$
$$
s = \sigma(a)
$$
$$
f(x, y) = \sigma(x + y)
$$

*Производная от функции нескольких переменных*
<br>
По х
$$
\frac{df}{dx} = \frac{d\sigma}{du}(\alpha(x, y)) * \frac{d\sigma}{dx}(x, y) = \frac{d\sigma}{du}(x + y) * \frac{d\sigma}{dx}(x, y)
$$

In [27]:
def assert_mulShape(X1: np.ndarray, X2: np.ndarray):
    assert X1.shape[1] == X2.shape[0], f'X1 should have shape {X2.shape[0]} while it has {X1.shape[1]}'

In [2]:
from typing import Callable 
import numpy as np
from typing import List

Array_Function = Callable[[np.ndarray], np.ndarray]

Chain = List[Array_Function]

In [3]:
def backward_multiple_add(x: np.ndarray, y: np.ndarray, sigma: Array_Function) -> float:
    a = x + y
    dsda = deriv(sigma, a)
    dadx, dady = 1, 1
    return dsda * dadx, dsda * dady

In [4]:
def matmul_forward(X: np.ndarray, W: np.ndarray) -> np.ndarray:
    assert X.shape[1] == W.shape[0]
    N = np.dot(X, W)
    return N

*Производные матриц*
<br>
Y = XW
$$
\frac{dY}{dX} = W^T
$$

In [8]:
def matmul_backward(X: np.ndarray, W: np.ndarray) -> np.ndarray:
    
    dYdX = np.transpose(W)
    
    return dYdX

$$
s = f(X, W) = \sigma(\nu(X, W)) = \sigma(x_1*w_1 + x_2*w_2 + x_3*w_3)
$$

In [16]:
def matrix_forward_extra(X: np.ndarray, W: np.ndarray, sigma: Array_Function) -> np.ndarray:
    
    assert X.shape[1] == W.shape[0], f'X should have shape {W.shape[0]} while it has {X.shape[1]}'
    
    N = X @ W
    print(N)
    S = sigma(N)
    
    return S

$$
\frac{df}{dX} = \frac{d\sigma}{du}(\nu(X,W)) * \frac{d\nu}{dX}(X,W)
$$

In [18]:
matrix_forward_extra(np.array([[1, 2, 3]]), np.array([3, 2, 1]), sigmoid)

[10]


array([0.9999546])

$$
\frac{df}{dX} = \frac{d\sigma}{du}(\nu(X,W)) * W^T
$$

In [28]:
def matrix_function_backward(X: np.ndarray, W: np.ndarray, sigma: Array_Function) -> np.ndarray:
    assert_mulShape(X, W)
    N = X @ W
    dS_dN = deriv(sigma, N)
    dNu_dX = matmul_backward(X, W)
    return dS_dN * dNu_dX

In [29]:
X = np.array([[0.4723, 0.6151, -1.7262]])
X

array([[ 0.4723,  0.6151, -1.7262]])

In [34]:
W = np.array([1, 1, 1])

In [35]:
matrix_function_backward(X, W, sigmoid)

array([0.22613525, 0.22613525, 0.22613525])